name: Authentication Sonar - DockerHub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest 
#    env:
#      Solution_Name: your-solution-name                         # Replace with your solution name, i.e. MyWpfApp.sln.
#      Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
#      Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
#      Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
       dotnet-version: 8.0.x
    - name: Install Sonnar Scanner Tool
      run:  dotnet tool install --global dotnet-sonarscanner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build and send to sonnar
      run: |         
          dotnet-sonarscanner begin /k:"FullHendrix_Authentication.Backend" /o:"fullhendrix" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build Intelica.Authentication.Backend/Intelica.Authentication.Backend.sln
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"      
    #- name: Create folfer
      #run: mkdir publish
    #- name: Publish
      #run: dotnet publish ./Intelica.Authentication.Backend/Intelica.Authentication.API/Intelica.Authentication.API.csproj --framework net8.0 -c Release -o ./publish
    #- name: Set up QEMU
      #uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:        
        username: ${{ secrets.DockerHubName }}
        password: ${{ secrets.DockerHubPassword }}
        ecr: false
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        push: true
        tags: fullhendrix/authentication.backend:latest
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #- name: Execute unit tests
      #run: dotnet build

    # Execute all unit tests in the solution
    #- name: Execute unit tests
      #run: dotnet test


